const careerData = [
    {
        "career-path": "Life Sciences",
        "career-category": "Science",
        "career-list": [
            {
                "career": "Marine Biologist",
                "image": "images/marine-biologist.jpg",
                "description-sinhala": "මුහුදු ගවේෂකයෙකු ලෙස ඔබේ දින ගත කිරීමට සිතන්න, ඩොල්ෆින්, ෂාර්ක් සහ ඉතා කුඩා ප්ලැන්ක්ටන් වැනි අපූර්ව සත්ත්වයන් සොයා බැලීමට ඔබ හැකිය.",
                "description-tamil": "கடல் உயிரியலாளராக உங்கள் நாட்களை கடலையும் அதில் வாழும் அதிசய உயிரினங்களைப் படிப்பதற்கும் கழிப்பதை கற்பனை செய்யுங்கள்!",
                "description": "Imagine spending your days exploring the ocean and studying all the amazing creatures like dolphins, sharks, and even tiny plankton! Marine biologists get to discover how these animals live, grow, and interact in their big, watery home."
            },
            {
                "career": "Geneticist",
                "image": "images/geneticist.jpg",
                "description-sinhala": "ජෙනටිකවේදීන් වන්නේ සියලු ජීවීන් තැනුණු නිල් සැලැස්ම් පිළිබඳව සැලසුම් කරන අපරාධ සහකරුවන් වේ.",
                "description-tamil": "உயிரினங்களின் உருவாக்க வரைபடங்களை ஆராய்கின்ற கண்டுபிடிப்பாளர்கள் போல ஜெனடிக் நிபுணர்கள்.",
                "description": "Geneticists are like detectives, peering closely at the blueprints that build all living things. These blueprints, called genes, contain the secrets to how creatures look, behave, and survive disease. Geneticists work in labs where they use technology to unlock these secrets. They help solve medical mysteries, contribute to curing diseases, and even help improve our foods. By studying genes, geneticists make it possible to predict health risks, offering personalized medicine tailored just for you, making them integral to the future of science and medicine."
            },
            {
                "career": "Microbiologist",
                "image": "images/geneticist.jpg",
                "description-sinhala": "සුළු ජීවීන් සහ සෛල ගැන අධ්යයනය කරන අදෘශ්ය ලෝකයේ ගවේෂකයන් වන මයික්‍රෝබයෝලජිස්ට්වරු.",
                "description-tamil": "தெரியாத உலகின் ஆராய்ச்சியாளர்களாக மைக்ரோபயாலஜிஸ்ட்கள், நுண்ணிய உயிரிகள் மற்றும் செல்களை ஆராய்கின்றனர்.",
                "description": "Microbiologists are the explorers of an invisible world, diving into the depths of cells and organisms that are too small to see without a microscope. They study bacteria, viruses, fungi, and other microorganisms that have a huge impact on our health, environment, and the planet. Their research helps us fight diseases by developing new medicines, such as antibiotics and vaccines. Microbiologists work in various fields, from food safety to environmental protection, ensuring that our drinking water is clean and our food is safe."
            },
            {
                "career": "Zoologist and Wildlife Biologist",
                "image": "images/geneticist.jpg",
                "description-sinhala": "ස්වාභාවික අවකාශ සොයන තවත් විද්යාවකින් යුත් වනජීවී බයෝලොජිස්ට්වරු සහ සොලෝජිස්ට්වරු ඔවුන්ගේ ස්වාභාවික අවකාශවල විවිධ සත්ත්ව ප්රජා පිළිබඳ අධ්යයනය කරයි.",
                "description-tamil": "விலங்கு உலகின் சாகசக்காரர்களாக வாழ்க்கையின் பியாலஜிஸ்ட்கள் மற்றும் சூழலியல் உயிரியலாளர்கள் வெவ்வேறு உயிரினங்களை அவற்றின் இயற்கை வாழிடங்களில் ஆராய்கின்றனர்.",
                "description": "Zoologists and wildlife biologists are the adventurers of the animal kingdom, studying various species in their natural habitats. They observe how animals interact within their ecosystems, tracking their behaviors, dietary habits, and reproductive cycles. This knowledge helps us understand environmental impacts and the importance of conservation efforts. By protecting animal habitats, we ensure biodiversity and a balanced ecosystem. These scientists often work outdoors in diverse settings, from rainforests to oceans, making their job an ongoing adventure with nature."
            },            
            {
                "career": "Epidemiologist",
                "image": "images/geneticist.jpg",
                "description-sinhala": "එපිඩිමියෝලොජිස්ට්ලා රෝග හා අනාවැකි ලෙස පසුපස යන අපරාධ හෙළිකරුවන් වැනිය. ඔවුහු රෝග ව්‍යාප්තවන අයුරු, බහුලව අවදානමට ලක්වන්නන් සහ අනාගතයේදී රෝග ව්‍යාප්තිය පාලනය හෝ නවත්වා ගැනීමට ක්‍රම හොයා බලන්නේය.",
                "description-tamil": "எபிடிமியோலஜிஸ்ட்கள் நோய்கள் மற்றும் கொள்ளைகளைப் பின்தொடரும் குற்றவியல் விசாரணையாளர்களைப் போன்றவர்கள். அவர்கள் நோய்கள் எவ்வாறு பரவுகின்றன, யார் அதிக அபாயத்திற்கு உள்ளாக்கப்படுகின்றனர் மற்றும் எதிர்கால நோய் தொற்றுகளை எவ்வாறு கட்டுப்படுத்த அல்லது நிறுத்த முடியும் என்பதைக் கண்டறிவார்கள்.",
                "description": "Epidemiologists are public health heroes who track diseases and outbreaks, much like detectives following clues. They study how diseases spread, who is most at risk, and how to control or stop future outbreaks. Using data and statistics, they map out patterns of illness and help public health officials make informed decisions to protect communities. Their work includes investigating outbreaks of diseases, like the flu or COVID-19, ensuring the public receives timely information and guidance on how to stay healthy."
            },
            {
                "career": "Neuroscientist",
                "image": "images/geneticist.jpg",
                "description-sinhala": "නියුරෝසයන්ත්‍රවේදීන්ගේ මොළයේ සංකීර්ණ නියුරෝන් ජාලයට අද්විතීය කුතුහලයක් ඇත. ඔවුහු මනෝ, ස්මෘති සහ හැඟීම් කෙසේ සැකසුණු බව පරීක්ෂා කරයි.",
                "description-tamil": "நரம்பியலாளர்கள் மூளையின் சிக்கலான நரம்பியல் நெட்வொர்க்கில் ஆர்வமுள்ளவர்கள், எவ்வாறு எண்ணங்கள், நினைவுகள் மற்றும் உணர்வுகள் செயலாக்கப்படுகின்றன என்பதை ஆராய்கின்றனர். இந்தத் துறை உளவியல், வேதியியல் மற்றும் உயிரியலை இணைக்கிறது, மூளையின் நடத்தை மற்றும் அறிவுசார் செயல்பாடுகளில் அதன் தாக்கத்தை புரிந்துகொள்ள உதவுகிறது. நரம்பியலாளர்கள் வெவ்வேறு செயல்பாடுகளின் போது அல்லது பல்வேறு நிலைகளில் மூளையில் என்ன நடக்கிறது என்பதைக் காண சோதனைகளை நடத்துகின்றனர். அவர்களது ஆராய்ச்சி மூளை நோய்களான அல்ஸைமர் மற்றும் பார்கின்சன் நோய்களுக்கான சிகிச்சைகளை உருவாக்க உதவுகிறது, இது மனித மனதின் மர்மங்களை அவிழ்க்க உதவும் முக்கிய பங்காற்றுகிறது.",
                "description": "Neuroscientists are fascinated by the brain's complex network of neurons, exploring how thoughts, memories, and emotions are processed. This field combines psychology, chemistry, and biology to understand the brain's impact on behavior and cognitive functions. Neuroscientists conduct experiments, sometimes using advanced imaging tools, to see what happens in the brain during different activities or under various conditions. Their research helps in developing treatments for brain diseases such as Alzheimer's and Parkinson's, making their role crucial in the quest to unlock the mysteries of the human mind."
            },
            {
                "career": "Botanist",
                "image": "images/geneticist.jpg",
                "description-sinhala": "පැළෑටි විද්‍යාඥයෝ ශාක විද්‍යාවට ආශාවෙන් යුතුව ඇති විද්‍යාඥයන් වේ. ඔවුහු සියලු ශාක ජීවිතය විමසා බලති, ශාක ක්‍රියාවලි හා ශාක අවට වාතාවරණයෙන් ශාක කෙසේ බලපෑමට ලක්වනවා දැයි අවබෝධ කිරීමට උත්සහ කරයි.",
                "description-tamil": "தாவரவியலாளர்கள் தாவரங்கள் மற்றும் அவற்றின் சுற்றுப்புறங்கள் மீது ஆர்வம் கொண்ட விஞ்ஞானிகள். அவர்கள் அனைத்து வகையான தாவர வாழ்க்கையை ஆராய்ந்து, தாவர செயல்முறைகள் மற்றும் சுற்றுப்புறத்தின் தாவரங்கள் மீது எவ்வாறு தாக்கம் அல்லது பாதிக்கப்படுகின்றன என்பதை புரிந்துகொள்ள முயற்சிக்கின்றனர்.",
                "description": "Botanists are scientists who have a passion for plants and their environments. They study all forms of plant life, aiming to understand plant processes and how plants affect and are affected by their environment. Their work is essential for sustainable management of natural resources, ensuring that we wisely use plants for food, medicine, and other needs. Botanists work in fields ranging from agriculture to conservation, helping to tackle challenges such as climate change and habitat loss. Their research is vital for maintaining the health of our planet."
            },
            {
                "career": "Medical Scientist",
                "image": "images/geneticist.jpg",
                "description-sinhala": "වෛද්‍ය විද්‍යාඥයෝ සෞඛ්‍ය සේවා නවෝත්පාදනයේ ඉදිරිපිටපෙළේ වෙති, රෝග විනිශ්චය කිරීම, ප්‍රතිකාර කිරීම සහ වැළැක්වීමේ ක්‍රම සොයාගැනීමේ පර්යේෂණ කළමනාකරණය කරයි.",
                "description-tamil": "மருத்துவ அறிவியலாளர்கள் நோய்களை கண்டறிதல், சிகிச்சைக்கு புதிய வழிகளை கண்டறிதல் மற்றும் நோய் தடுப்புக்கான ஆய்வுகளை மேற்கொள்கின்ற சுகாதார புதுமையின் முன்னணியில் உள்ளனர்.",
                "description": "Medical scientists are at the forefront of healthcare innovation, conducting research that leads to better ways of diagnosing, treating, and preventing diseases. They work in laboratories and clinical settings, studying biological systems to understand the causes of diseases and their effects on the human body. By developing and testing medical treatments, they contribute to public health by improving medical practices and patient outcomes. Their research is critical, especially in developing vaccines and new therapeutic techniques, which play significant roles in improving global health standards."
            },
            {
                "career": "Pharmacologist",
                "image": "images/geneticist.jpg",
                "description-sinhala": "ඖෂධ විද්‍යාඥයෝ ජීව පද්ධති සමඟ ඖෂධ අන්තර්ක්‍රියා කරන අයුරු විමසා බලන අතර, ඖෂධ ප්‍රතිඵල, විශේෂීකරණය සහ අවාසි හැකියාවන් අවම කිරීම ඉලක්ක කරගෙන යයි.",
                "description-tamil": "மருந்தியலாளர்கள் உயிரியல் அமைப்புகளுடன் மருந்துகள் எவ்வாறு செயல்படுகின்றன என்பதை ஆராய்ந்து, மருந்துகளின் பலன்களை மேம்படுத்துவதும் பக்க விளைவுகளை குறைப்பதும் அவர்களது குறிக்கோளாக உள்ளது.",
                "description": "Pharmacologists are experts in the science of drugs and their effects on living systems. They study how drugs interact with biological systems, aiming to understand and predict the effects of drugs, improve their efficacy, and minimize side effects. Their work is crucial in the development of new medicines and therapies, impacting fields from cancer treatment to mental health. Pharmacologists play a key role in medical research and development, ensuring that new treatments are both safe and effective, thereby improving patient care and health outcomes."
            }
        ]
    },
    {
        "career-path": "Physical Sciences",
        "career-category": "Science",
        "career-list": [
            {"career": "Geologist", "image": "images/geneticist.jpg", "description": "Geologists are like Earth detectives who explore rocks, mountains, and even volcanoes to learn about our planet's past and predict its future. They get to travel and see incredible natural wonders while solving Earth’s mysteries!"},
            {"career": "Astronomer", "image": "images/geneticist.jpg", "description": "Astronomers are star and planet explorers! They use big telescopes to look deep into space and learn about galaxies, stars, and planets far away. Imagine spending your nights stargazing and discovering new worlds!"},
            {"career": "Atmospheric Scientist", "image": "images/geneticist.jpg", "description": "Atmospheric scientists study the air around us. They predict the weather, learn about climates, and even track hurricanes from space. It’s like being a weather wizard, helping us stay safe and prepared for any weather!"},
            {"career": "Chemist", "image": "images/geneticist.jpg", "description": "Chemists mix and play with different substances to create amazing things like medicines and clean energy. It’s a lot like being a wizard, but with chemicals instead of magic spells!"},
            {"career": "Environmental Scientist", "image": "images/geneticist.jpg", "description": "Environmental scientists are our planet's heroes! They work to solve problems like pollution and climate change, helping to keep the air, water, and land clean and safe for animals and people alike."},
            {"career": "Conservation Scientist", "image": "images/geneticist.jpg", "description": "Conservation scientists are guardians of nature, working to protect and restore forests, rivers, and other natural areas. They make sure animals have homes and that nature stays beautiful and healthy for everyone."},
            {"career": "Geographer", "image": "images/geneticist.jpg", "description": "Geographers are map makers and travelers at heart! They explore different places and study the land, cultures, and people. They help us understand how the world’s pieces fit together like a giant puzzle."},
            {"career": "Forensic Scientist", "image": "images/geneticist.jpg", "description": "Forensic scientists are like detectives for the law, using science to solve mysteries and find out the truth in crime scenes. They help solve cases by looking at clues so tiny you need a microscope to see them!"},
            {"career": "Materials Scientist", "image": "images/geneticist.jpg", "description": "Materials scientists invent stuff by understanding and manipulating the stuff everything is made from! They create new materials that make our phones, cars, and even clothes better and smarter."}
        ]
               
    },
    {
        "career-path": "Information Technology",
        "career-category": "Technology",
        "career-list": [
            {"career": "Software Engineer", "image": "images/software-engineer.jpg", "description": "Software engineers are like digital architects. They create the apps and programs that you use on your computers and smartphones! From games to social media apps, they write special codes to tell the computer what to do, making sure everything works smoothly and is fun to use."},
            {"career": "Cybersecurity Analyst", "image": "images/cybersecurity-analyst.jpg", "description": "Cybersecurity analysts are like internet superheroes. They protect computers and networks from sneaky hackers who try to steal important information. They set up strong defenses and keep an eye on computer systems to make sure no one can break in."},
            {"career": "Game Developer", "image": "images/game-developer.jpg", "description": "Game developers are the masterminds behind your favorite video games. They imagine the story, create the characters, and build the game world. It’s like using magic to turn their ideas into games that you can play on consoles, computers, or phones."},
            {"career": "Web Developer", "image": "images/web-developer.jpg", "description": "Web developers are the builders of the internet. They create websites where you can play, learn, shop, and watch videos. They use a mix of coding and creativity to make sure websites look good and are easy to use."},
            {"career": "Network Engineer", "image": "images/network-engineer.jpg", "description": "Network engineers are like traffic controllers for the internet. They set up and look after networks to make sure data flows smoothly without interruption. Their job is to connect computers and make sure they can talk to each other without problems."},
            {"career": "Mechatronics Engineer", "image": "images/mechatronics-engineer.jpg", "description": "Mechatronics engineers are inventors who combine mechanics, electronics, and computing to make smart machines and robots. They work on cool projects like designing robotic arms, smart cars, and even automated systems that help in factories."},
            {"career": "Systems Analyst", "image": "images/systems-analyst.jpg", "description": "Systems analysts are tech detectives. They look closely at computer systems to find ways to make them better. They solve puzzles about software and hardware to help everyone use technology more easily."},
            {"career": "Cloud Solutions Architect", "image": "images/cloud-solutions-architect.jpg", "description": "Cloud solutions architects design the 'clouds' where data is stored so that you can access your photos, videos, and files from anywhere in the world. They create plans to build these clouds, making sure they are safe and easy to use."},
            {"career": "IT Project Manager", "image": "images/it-project-manager.jpg", "description": "IT project managers are like captains of technology teams. They make sure that tech projects, like creating new software or installing new computer systems, are finished on time and work well. They plan, organize, and direct teams to achieve their tech goals."},
            {"career": "Data Security Analyst", "image": "images/data-security-analyst.jpg", "description": "Data security analysts keep important information safe from hackers. They act like guards, setting up protections for data like your schoolwork or family photos to make sure nobody can steal or peek at it."},
            {"career": "Embedded Systems Engineer", "image": "images/embedded-systems-engineer.jpg", "description": "Embedded systems engineers create smart machines by putting tiny computers into devices like cameras, cars, and even household appliances. They make sure these gadgets can think and act on their own, making our lives easier and more fun."},
            {"career": "Systems Engineer", "image": "images/systems-engineer.jpg", "description": "Systems engineers are the master planners who design and manage complex systems. They make sure everything works well together, from computers and networks to software and security, ensuring everything runs smoothly without glitches."}
        ]        
    },
    {
        "career-path": "Data Sciences",
        "career-category": "Technology",
        "career-list": [
            {"career": "Data Analyst", "image": "images/data-analyst.jpg", "description": "Data Analysts are like treasure hunters who use computers to find important clues hidden in numbers and information. They look at lots of data—like scores from your favorite games or sales from ice cream shops—to figure out patterns and solve puzzles. This helps companies make better decisions, like knowing what new ice cream flavor to create or how to make a game more fun."},
            {"career": "AI/ML Engineer", "image": "images/ai-ml-engineer.jpg", "description": "AI/ML Engineers are the wizards of the computer world. They teach computers how to learn on their own, kind of like how you learn to get better at a video game. They create smart machines that can do amazing things like recognize pictures, understand spoken words, or even drive cars by themselves!"},
            {"career": "Business Intelligence Analyst", "image": "images/business-intelligence-analyst.jpg", "description": "Business Intelligence Analysts are like detectives for companies. They use tools to look closely at information and find out secrets about what sells best or what customers like. Their work helps businesses decide what products to sell more of or what new products to make to keep customers happy."},
            {"career": "Database Administrator", "image": "images/database-administrator.jpg", "description": "Database Administrators are the keepers of information. They use special computer programs to store tons of data safely, like all the levels in a video game or scores from sports matches. They make sure this information is safe and ready to use whenever someone needs it, ensuring that everything is organized and runs smoothly."},
            {"career": "Data Engineer", "image": "images/data-engineer.jpg", "description": "Data Engineers build the hidden tracks that information travels on within computers. They connect different data sources—like your school's computer, the library, and online resources—so all this information can flow and be used together. It’s a bit like building a model train set, but instead of trains, they work with streams of data!"},
            {"career": "Data Architect", "image": "images/data-architect.jpg", "description": "Data Architects design the blueprints for data systems, kind of like how architects design buildings but for computer data. They plan out where data should go, how it moves, and who can see it, making sure everything fits together perfectly for the businesses. Their plans help everyone in a company find the data they need quickly and use it effectively."},
            {"career": "Quantitative Analyst", "image": "images/quantitative-analyst.jpg", "description": "Quantitative Analysts are math superstars who use their skills to help banks and businesses make smart decisions about money. They look at numbers and trends to predict what will happen in the future, like whether prices for toys or games might go up. They use special math tricks to guess these things, helping their companies succeed."},
            {"career": "Machine Learning Scientist", "image": "images/machine-learning-scientist.jpg", "description": "Machine Learning Scientists are the creators of learning computers. They explore ways to make machines smarter, teaching them to understand pictures, words, or even your handwriting. These scientists use their knowledge to make apps and devices that can help you in daily life, like a phone that recognizes your face or a game that learns how you play."},
            {"career": "Statistical Learning Analyst", "image": "images/statistical-learning-analyst.jpg", "description": "Statistical Learning Analysts use their super sharp math skills to find patterns in data. Imagine being able to predict where a soccer ball will land or which TV show will become popular! These analysts study the data from the past to make predictions about the future, helping companies and people make better choices every day."}
        ]
        
    },
    {
        "career-path": "Core Engineering",
        "career-category": "Engineering",
        "career-list": [
            {"career": "Biomedical Engineer", "image": "images/biomedical-engineer.jpg", "description": "Biomedical engineers are like superheroes who use their engineering superpowers to help doctors save lives. They design cool gadgets and machines that doctors use in hospitals to check if you’re healthy or to fix bones and muscles. For example, they make things like heart monitors, artificial limbs, and even machines that can look inside your body without surgery! They combine medicine and engineering to make sure these tools are safe and work perfectly to help patients get better."},
            {"career": "Civil Engineer", "image": "images/civil-engineer.jpg", "description": "Civil engineers are the master builders of our world! They design and supervise the construction of amazing things like bridges, skyscrapers, and roads. Imagine playing with building blocks, but on a giant scale, and those blocks are used to build playgrounds, schools, and even the roads your family drives on. Civil engineers make sure all these structures are strong and safe, planning out every detail from the ground up."},
            {"career": "Mechanical Engineer", "image": "images/mechanical-engineer.jpg", "description": "Mechanical engineers are inventors and problem solvers who work with anything that moves. They design and build all sorts of machines, from tiny parts inside a watch to huge engines that power airplanes. They figure out how things work and come up with new ideas to make them better—like making cars faster or more fuel-efficient, or designing roller coasters that give the most thrills without the spills."},
            {"career": "Electrical Engineer", "image": "images/electrical-engineer.jpg", "description": "Electrical engineers are like wizards of electricity! They design and create everything that uses electricity to work, which includes all the gadgets at home like your TV, computer, and even the lights. They make sure that these gadgets are not only fun but also safe to use. Electrical engineers also work on bigger projects like power stations or smart grids that help cities keep the lights on and the energy flowing."},
            {"career": "Chemical Engineer", "image": "images/chemical-engineer.jpg", "description": "Chemical engineers are like chefs who mix different ingredients, but instead of making food, they create amazing new materials and products. They work with chemicals to invent everything from medicines and foods to plastics and fuels. They figure out how to turn raw materials like oil and minerals into cool, useful stuff we use every day. Chemical engineers also help solve problems like pollution and find ways to make manufacturing safer and cleaner."},
            {"career": "Industrial Engineer", "image": "images/industrial-engineer.jpg", "description": "Industrial engineers make sure that factories and systems run smoothly, quickly, and efficiently. They figure out the best ways to make products, manage people, and use machines to get the job done well. Think of them like the organizers of a huge party where they need to make sure everything happens on time and everyone has a good time, but for factories that make your toys, cars, and even candy!"},
            {"career": "Automotive Engineer", "image": "images/automotive-engineer.jpg", "description": "Automotive engineers are the brains behind the cars and trucks that zoom on the streets. They design new vehicles, dreaming up everything from the shape of the car to the way it feels to drive it. They test cars to make sure they are safe and fun to drive. Automotive engineers work on all kinds of vehicle systems like engines, brakes, and air conditioning, making sure everything works perfectly together."},
            {"career": "Nanotechnology Engineer", "image": "images/nanotechnology-engineer.jpg", "description": "Nanotechnology engineers work with super tiny things that are almost impossible to see, even with a microscope! They create new materials and devices at an incredibly small scale, like making computer chips smaller but more powerful, or developing new medicines that can fight diseases better. Their work might sound like science fiction, but they are making it real, helping build the future of technology and medicine."},
            {"career": "Energy Systems Engineer", "image": "images/energy-systems-engineer.jpg", "description": "Energy systems engineers are like the eco-warriors of engineering. They develop ways to generate, store, and use energy from sources like the sun, wind, and water. Their goal is to make energy use as clean and efficient as possible to help keep our planet healthy. They work on cool projects like solar panels that power homes and wind turbines that produce electricity without polluting."},
            {"career": "Robotics Engineer", "image": "images/robotics-engineer.jpg", "description": "Robotics engineers are the creators of robots. They design, build, and test robots that can do jobs like assembling cars, exploring space, or even helping in surgeries. These engineers use their skills in mechanics, electronics, and computer programming to make robots that can move, sense, and interact with the world. It’s like bringing a robot to life and teaching it to perform tasks, sometimes even using artificial intelligence to make it smarter!"}
        ]
        
    },
    {
        "career-path": "Mathematical",
        "career-category": "Mathematics",
        "career-list": [
            {"career": "Mathematician", "image": "images/mathematician.jpg", "description": "Mathematicians are like puzzle solvers who use numbers and formulas to figure out problems. They explore and create new ways of thinking about the world through numbers. Mathematicians work on cool stuff like discovering patterns in nature, designing computer games, or even predicting what might happen in the future. They play with theories and solve mathematical mysteries, making them the great adventurers of the math world!"},
            {"career": "Statistician", "image": "images/statistician.jpg", "description": "Statisticians are like detectives with numbers. They gather data, which is just a fancy word for information, and use it to solve real-world mysteries. Whether it’s figuring out what makes a toy popular or predicting the weather, statisticians use their skills to help make sense of the world. They use graphs, charts, and computers to turn confusing numbers into clear stories everyone can understand."},
            {"career": "Actuary", "image": "images/actuary.jpg", "description": "Actuaries are super smart math experts who help companies predict the future and make plans for it. They look at patterns in data, like when people buy toys or how often they go to the doctor, to guess what could happen next. Actuaries are really important in insurance companies where they help decide how much people should pay for their insurance by figuring out the chances of things like car accidents or houses getting damaged."},
            {"career": "Cryptographer", "image": "images/cryptographer.jpg", "description": "Cryptographers are like secret keepers. They create special codes that keep our digital information safe. Every time you send a message on your phone or log into a game, cryptographers' codes protect your secrets from hackers. They use complex math to build these invisible locks and keys, making sure only the right people can unlock the messages."},
            {"career": "Data Scientist", "image": "images/data-scientist.jpg", "description": "Data scientists are modern-day explorers who use their super-smart math and computer skills to find hidden treasures in mountains of data. They look at information from places like websites, shops, or games to find patterns that can tell us cool things, like what the next big toy trend might be. They help companies understand what people like and don’t like, making them really important in deciding what new products to create."},
            {"career": "Financial Analyst", "image": "images/financial-analyst.jpg", "description": "Financial analysts are like fortune tellers for businesses, but instead of using crystal balls, they use numbers and charts. They look at a company's money—how much they earn and spend—to help predict if the company will do well in the future. This helps people decide if they should invest money in these companies. Financial analysts are key players in helping people make smart choices with their money."},
            {"career": "Quantitative Risk Analyst", "image": "images/quantitative-risk-analyst.jpg", "description": "Quantitative risk analysts are like weather forecasters for the financial world. They use math to predict risky situations for companies, like financial storms that could cause trouble. By understanding these risks, they help companies prepare and protect themselves, just like how you might carry an umbrella if you knew it was going to rain."},
            {"career": "Quantitative Analyst", "image": "images/quantitative-analyst.jpg", "description": "Quantitative analysts, or 'quants' as they’re often called, are like the masterminds of the financial world. They use math and computer programs to help banks and investment firms make big decisions about money. They build models that can predict things like which stocks will go up in price and when might be the best time to buy or sell them. Quants combine their love of math with finance to solve complex puzzles every day."}
        ]
        
    }
]
